INSERT INTO ecommerce_db.products (name, description, price, stock, createdAt, updatedAt) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with USB receiver', 599.00, 120, NOW(), NOW()),
('Gaming Keyboard', 'Mechanical RGusersB backlit gaming keyboard', 2499.00, 80, NOW(), NOW()),
('Bluetooth Speaker', 'Portable Bluetooth speaker with deep bass', 1799.00, 60, NOW(), NOW()),
('Smart Watch', 'Fitness tracking smartwatch with heart rate monitor', 3999.00, 45, NOW(), NOW()),
('USB-C Charger', 'Fast charging 65W USB-C power adapter', 1299.00, 150, NOW(), NOW()),
('Power Bank', '10000mAh fast charging power bank', 999.00, 200, NOW(), NOW()),
('Laptop Stand', 'Adjustable aluminum laptop cooling stand', 699.00, 75, NOW(), NOW()),
('External Hard Drive', '1TB portable external HDD', 3499.00, 30, NOW(), NOW()),
('Wireless Earbuds', 'True wireless earbuds with noise cancellation', 2999.00, 90, NOW(), NOW()),
('Webcam', 'Full HD 1080p webcam with microphone', 1599.00, 65, NOW(), NOW()),
('HDMI Cable', '2m high-speed HDMI cable', 299.00, 300, NOW(), NOW()),
('Graphics Tablet', 'Digital drawing tablet with pen', 5499.00, 25, NOW(), NOW()),
('Portable SSD', '500GB high-speed portable SSD', 5999.00, 20, NOW(), NOW()),
('LED Desk Lamp', 'Rechargeable LED desk lamp with dimmer', 799.00, 100, NOW(), NOW()),
('Smartphone Gimbal', '3-axis handheld smartphone gimbal stabilizer', 7499.00, 15, NOW(), NOW()),
('Noise Cancelling Headphones', 'Over-ear ANC Bluetooth headphones', 6499.00, 40, NOW(), NOW()),
('VR Headset', 'Virtual reality headset for gaming', 12999.00, 10, NOW(), NOW()),
('Smart Plug', 'Wi-Fi smart plug with Alexa/Google support', 499.00, 180, NOW(), NOW()),
('WiFi Router', 'Dual-band high-speed Wi-Fi 6 router', 3299.00, 55, NOW(), NOW()),
('Portable Projector', 'Mini portable projector for movies', 8499.00, 12, NOW(), NOW()),
('Wireless Charging Pad', 'Fast wireless charging pad for smartphones', 1199.00, 85, NOW(), NOW()),
('Smart Bulb', 'Wi-Fi smart bulb with RGB color change', 399.00, 250, NOW(), NOW()),
('Electric Kettle', '1.5L stainless steel electric kettle', 999.00, 110, NOW(), NOW()),
('Air Purifier', 'HEPA filter home air purifier', 7999.00, 18, NOW(), NOW()),
('Laptop Cooling Pad', '5-fan laptop cooling pad with RGB lights', 1599.00, 50, NOW(), NOW()),
('Action Camera', '4K waterproof action camera', 5499.00, 22, NOW(), NOW()),
('Smart Door Lock', 'Fingerprint and keypad smart door lock', 11999.00, 8, NOW(), NOW()),
('Mechanical Pencil', '0.5mm precision mechanical pencil', 199.00, 500, NOW(), NOW()),
('Office Chair', 'Ergonomic office chair with lumbar support', 5999.00, 14, NOW(), NOW()),
('Monitor Stand', 'Adjustable dual monitor stand', 2499.00, 35, NOW(), NOW());
